# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Update CocoaPods Dependencies

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  update_pods:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: actions/setup-xcode@v3
        with:
          version: '15.4'  # Or specify the desired Xcode version

      - name: Use Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cocoapods/repos
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Update Pods
        run: |
          cd ios  # Navigate to your iOS project directory
          pod update

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update CocoaPods dependencies'
          branch: main  # Or your desired branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
